---
- name: Web Server
  hosts: server
  become: true
  vars:
    db_host: "{{ db_host }}"
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_pass: "{{ db_pass }}"
  roles:
    - server

- name: DB Server
  hosts: db
  become: true
  vars:
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_pass: "{{ db_pass }}"
  roles:
    - db
